version: '3'
services:
  php8:
    container_name: dwcs-php8
    #image: phpstorm/php-apache:8.2-xdebug3.2
    build:
         context: .
         dockerfile: Dockerfile
    hostname: php82-xdebug32
    volumes:
      - ./config/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - './www/:/var/www/html'
    ports:
      - "8080:80"
    working_dir: /var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9003 remote_enable=1
    networks:
      - dwcs


#  php7:
#    container_name: dwcs-php7
#    #image: phpstorm/php-apache:8.2-xdebug3.2
#    build:
#      context: .
#      dockerfile: Dockerfile-php7
#    hostname: php74-xdebug32
#    volumes:
#      - ./config/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
#      - ./config/php.ini:/usr/local/etc/php/php.ini
#      - './www/:/var/www/html'
#    ports:
#      - "8081:80"
#    working_dir: /var/www/html
#    environment:
#      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9003 remote_enable=1
#    networks:
#      - dwcs
#    # wait to php8 to be ready
#    depends_on:
#      - php8


  mysql:
    container_name: dwcs-mysql
    image: mysql:8.0
    hostname: mysql8
    volumes:
      - dwcs-db:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dwcs
      MYSQL_USER: dwcs
      MYSQL_PASSWORD: dwcs
    networks:
      - dwcsLan
      - dwcs

networks:
  dwcsLan:
    internal: true
  dwcs:
    driver: bridge
volumes:
  dwcs-db: