version: '3'
services:
  php8:
    container_name: dwcs-php8
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - './config/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini'
      - './config/php/php.ini:/usr/local/etc/php/php.ini'
      - './config/apache2/apache2.conf:/etc/apache2/apache2.conf'
      - './config/apache2/ports.conf:/etc/apache2/ports.conf'
      - './config/apache2/sites-available/:/etc/apache2/sites-available'
      - './config/apache2/sites-enabled/:/etc/apache2/sites-enabled'
      - './config/apache2/sites-available/:/etc/apache2/sites-available/'
      - './config/apache2/mods-available/:/etc/apache2/mods-available/'
      - './www/:/var/www'
    ports:
      - "8080:80"
    tty: true
    user: 1000:1000
    working_dir: /var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9003 remote_enable=1
    networks:
      - dwcs

  dns:
    image: ubuntu/bind9
    container_name: dwcs-dns
    volumes:
      - ./config/dns:/etc/bind
    ports:
      - "53:53"
      - "53:53/udp"
    networks:
      - dwcs

  mysql:
    container_name: dwcs-mysql
    image: mysql:latest
    volumes:
      - dwcs-db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: dwcs
    networks:
      - dwcsLan
      - dwcs

  phpmyadmin:
    container_name: dwcs-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    hostname: phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dwcs

    networks:
      - dwcsLan
      - dwcs

networks:
  dwcsLan:
    internal: true
  dwcs:
    driver: bridge
volumes:
  dwcs-db: